# Generated by Django 5.2.6 on 2026-03-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='otp_last_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
